---
- name: "instalar servidor httpd"
  hosts: app1
  tasks:
    - name: "instalar paquetes"
      shell: "amazon-linux-extras enable nginx1"

    - name: "instalar nginx"
      shell: "amazon-linux-extras install nginx1 -y"

    - name: "start nginx"
      service:
        name: nginx
        state: started
      become: true